/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author PC-GSM15
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Dato1 = new java.awt.TextField();
        Operador = new java.awt.TextField();
        Dato2 = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(930, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Consumiendo Web Service SOAP...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 0, 413, 29);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CALCULADORA");

        Dato1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Dato1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Dato1.setText("Dato 1");
        Dato1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dato1MouseClicked(evt);
            }
        });

        Operador.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Operador.setText("Operador");
        Operador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OperadorMouseClicked(evt);
            }
        });
        Operador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorActionPerformed(evt);
            }
        });

        Dato2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Dato2.setText("Dato 2");
        Dato2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dato2MouseClicked(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("PARA OCUPAR UN OPERADOR\nELIJA LAS SIGUIENTES OPCIONES\n1.- SUMA\n2.- RESTA\n3.-MULTIPLICACION");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("=");

        resultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultado.setName("id"); // NOI18N

        btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn.setText("Resultado");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(Dato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dato1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Operador, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dato2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(28, 28, 28)
                .addComponent(btn)
                .addGap(47, 47, 47))
        );

        resultado.getAccessibleContext().setAccessibleName("id");

        getContentPane().add(panel);
        panel.setBounds(260, 60, 550, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperadorActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        int numero = Integer.parseInt(Dato1.getText());
        int numero2 = Integer.parseInt(Dato2.getText());
        int operador = Integer.parseInt(Operador.getText());
        int resultadoFinal = calculadora(numero, numero2, operador);
        resultado.setText(""+resultadoFinal);
         
    }//GEN-LAST:event_btnActionPerformed

    private void Dato1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dato1MouseClicked
        Dato1.setText("");
    }//GEN-LAST:event_Dato1MouseClicked

    private void OperadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OperadorMouseClicked
       Operador.setText("");
    }//GEN-LAST:event_OperadorMouseClicked

    private void Dato2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dato2MouseClicked
        Dato2.setText("");
    }//GEN-LAST:event_Dato2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Dato1;
    private java.awt.TextField Dato2;
    private java.awt.TextField Operador;
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables

    private static int calculadora(int dato1, int dato2, int operador) {
        WS.Calculadora_Service service = new WS.Calculadora_Service();
        WS.Calculadora port = service.getCalculadoraPort();
        return port.calculadora(dato1, dato2, operador);
    }
}
